ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      # - id: ruff-format

